services:
  mailrelay:
    image: boky/postfix:${MAILRELAY_VERSION:?required}
    container_name: mailrelay
    restart: unless-stopped
    env_file: .env
    environment:
      ALLOWED_SENDER_DOMAINS: ${ALLOWED_SENDER_DOMAINS:?required}
      DKIM_AUTOGENERATE: "true"
      POSTFIX_myhostname: ${MAILRELAY_HOSTNAME:?required}
      POSTFIX_smtpd_tls_security_level: none
      POSTFIX_inet_protocols: ipv4
    volumes:
      - ./.docker/mailrelay/data:/etc/opendkim/keys
    networks:
      - mail-network
    healthcheck:
      test: ["CMD-SHELL", "postfix status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


networks:
  mail-network:
    external: true
